### ISSUE TITLE
GAMS solver

### ISSUE THREAD

**Issue by infsum** [olugovoy/energyRt#7]
Hi, oleg, it's been a while. I got a problem in calculating the levcost using the GAMS sovler
as follows.  I use the latest version of GAMS 25.1.3，with demo license. So if want to use the GAMS solver, I have to get buy the license?
`
> lc.CHPGAS <- levcost(CHPGAS, start_year = 2015, 
+                      discount = 0.1, 
+                      price = price,
+                      solver = "GAMS")
Preprocessing time: 0.78s
Error in doTryCatch(return(expr), name, parentenv, handler) : 
  Solution error code 127
`

**Comment by olugovoy** [comment]
Hi @infsum,
Yes, to use GAMS you need to obtain GAMS license with an LP solver (CBC is included in GAMS base and works well for mid-scale models, CPLEX is preferred for large-scale models). But for levcost and small models you can use GLPK which is free. We have in plans adding Julia version (with CBC and other solvers), though it is in a long list...
